### ISSUE TITLE
`every` statement does not operate correctly on non-collections

### ISSUE THREAD

**Issue by anakrish** [microsoft/rego-cpp#113]
```rego
package test

import future.keywords.every

x = y {
	every a in 1 {
		a > 0
	}
	y = 5
}
```

Produces no output.

**Comment by matajoh** [comment]
So just looping back but I think moving forward "no output" is the intended behaviour. For example, see the discussion here:

https://github.com/open-policy-agent/opa/issues/6762

And also this test from the test suite (which passes):

```yaml
  - note: "every/non-iter domain: int"
    modules:
      - |
        package test
        import future.keywords.every

        default p := 1

        p := 2 {
          every v in 42 { v > 1 }
        }
    query: data.test.p = x
    want_result:
      - x: 1
  ```
